#!/bin/bash
# WJTTC Pre-Commit Hook
# Rocket Science-Grade Testing Enforcement
#
# Generated by: wjttc init
# Learn more: https://wjttc.dev

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 WJTTC Pre-Commit Certification"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Run TypeScript type check
echo "📝 TypeScript strict mode check..."
npm run typecheck
if [ $? -ne 0 ]; then
  echo ""
  echo "❌ TypeScript errors detected"
  echo "Fix type errors before committing"
  echo "Rocket science demands zero errors"
  exit 1
fi
echo "✅ TypeScript: Zero errors"
echo ""

# Run critical "brake" tests (fast subset ~5-30s)
echo "🏆 Running critical brake tests..."
npm run test:brake
if [ $? -ne 0 ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "❌ WJTTC CERTIFICATION FAILED"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "Tests must pass before commit."
  echo "No exceptions. No shortcuts."
  echo ""
  echo "SpaceX doesn't launch untested rockets."
  echo "We don't ship untested code."
  echo ""
  echo "Fix failing tests and try again."
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ WJTTC CERTIFICATION: PASSED 🏆"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Status: Rocket-ready 🚀"
echo "Proceeding with commit..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

exit 0
